name: Laravel CI/CD

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, mysqli, pdo, pdo_mysql, zip, exif, pcntl, bcmath

    - name: Cache Composer dependencies
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Install dependencies
      run: composer install --no-progress --no-suggest

    - name: Generate new key
      run : cp .env.example .env && php artisan key:generate

    - name: Run tests
      run: php artisan test

  deploy_main:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: 136.244.94.130
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: cd /var/www/prod/deploy-laravel && git pull origin main && yes | composer install --no-progress --no-suggest && php artisan migrate --force

  deploy_dev:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: 136.244.94.130
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: cd /var/www/test/deploy-laravel && git checkout dev && git pull origin dev && yes | composer install --no-progress && php artisan migrate --force && php artisan optimize


